name: Discord webhook for Open PS2 Loader releases 
on:
  workflow_dispatch:
  release:
    types: [released]
jobs:
  OPL-Release_webhook:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v2.0.2
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_NEWS_CHANNEL }}
          content: "Hey @everyone! **OPL**  **${{ env.RELEASE_VERSION }}** has been released!"
